config/routes.rb
Web::Application.routes.draw do

  resources :user_location_asset

  resources :user_location_tagged_users

  namespace :admin do
    resources :users do
      member do
        get :impersonate
      end
    end
    resources :communities
  end

  match 'mission', :to => 'pages#mission'
  match 'about', :to => 'pages#about'
  match 'team', :to => 'pages#team'
  match 'privacy', :to => 'pages#privacy'
  match 'tos', :to => 'pages#tos'
  match 'faq', :to => 'pages#faq'
  match 'feedback', :to => 'pages#feedback'
  match 'jobs', :to => 'pages#jobs'
  match 'api', :to => 'pages#api'
  match 'maintenance', :to => 'pages#maintenance'
  match 'happy_customers', :to => 'pages#happy_customers'
  match 'community_guidelines', :to => 'pages#community_guidelines'
  match 'checking_in', :to => 'pages#checking_in'
  match 'welcome_kits', :to => 'pages#welcome_kits'
  match 'location_aware_group_management', :to => 'pages#location_aware_group_management'
  match 'conferences', :to => 'pages#conferences'
  match 'welcome_kits_b', :to => 'pages#welcome_kits_b'
  match 'special_thanks', :to => 'pages#special_thanks'
  match 'community_pages', :to => 'pages#community_pages'
  match 'support_us', :to => 'pages#support_us'
  match 'community_pages_community_builders', :to => 'pages#community_pages_community_builders'
  match 'communities_beta', :to => 'pages#communities_beta'
  match 'travatar', :to => 'pages#travatar'
  match 'colophon', :to => 'pages#colophon'

  get "twilio/process_sms"

  match 'twilio/process_sms' => 'twilio#process_sms'

  namespace :admin do resources :beta_access_requests end

  namespace :admin do resources :registration_codes end

  namespace :admin do resources :dashboard end

  namespace :admin do resources :countries end

  namespace :admin do resources :languages end

  namespace :admin do resources :beta_users end

  get "omniauth_callbacks_controller/facebook"

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", passwords: "passwords", confirmations: "confirmations" } do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  devise_scope :user do
    match "/users/auth/facebook/setup" => "users/omniauth_callbacks#setup"
    match "/users/auth/facebook" => "users/omniauth_callbacks#facebook"
    match "/users/auth/facebook/callback" => "users/omniauth_callbacks#facebook"
    match "/users/auth/twitter" => "users/omniauth_callbacks#twitter"
    match "/users/auth/twitter/callback" => "users/omniauth_callbacks#twitter"
  end

  match 'users/tags(/:perma_list)' => 'users#tags', :as => 'users_tags'

  namespace :api do
    devise_for :users

    resources :users, :except=>[:destroy] do
      member do
        get 'badge'
      end
      collection do
        get 'notification_contact_details'
      end
    end

    resources :locations, :except=>[:destroy] do
      collection do
        get 'search'
      end
    end

    resources :user_locations do
      member do
        get 'user_friends_not_ohw_user'
        get 'users_at_location'
        get 'user_friends_ohw_user'
      end
    end

    resources :user_friends do
    end

    resources :user_provider_friends do
    end

    resources :user_assets do
    end

    resources :languages do
    end

    resources :user_languages do
      collection do
        put 'mass_update'
      end
    end

    resources :notification_contact_details do
    end
  end

  resources "user_provider_friends" do
    collection do
      get 'follow'
    end
  end

  resources "user_friends" do
    collection do
      get 'network'
      get 'dashboard'
      get 'travel_feed', to: 'user_friends#dashboard'
      get 'grouped_friends'
      put 'update_tag'
      get 'following/:user_id', :action => 'following', :as => 'following'
      get 'followers/:user_id', :action => 'followers', :as => 'followers'
      put :send_invitation_email
    end
  end

  resources :provider_friends do
    collection do
      get 'network'
      get 'grouped_friends'
    end
  end

  resources :locations do
    collection do
      get 'provider_friends'
    end
  end

  resources :user_searches do
    collection do
      get :site_search
      get :search_users
    end
    member do
      get :more_users_with_tag
      get :more_friends
    end
  end

  resources :beta_users

  resources :beta_access_requests

  resources :notification_contact_details

  resources :user_contacts

  resources :user_city_tips do
    member do
      put :like_city_tip
    end
  end

  resources :user_cities do
    member do
    end
    collection do
    end
  end

  match 'city_tips/:city_id(/:user_id)' => 'user_cities', action: 'city_tips', as: 'city_tips', via: [:get]

  resources :preferences

  match 'users/registration_code' => 'users#registration_code', via: [:get]
  match 'users/awaiting_confirmation' => 'users#awaiting_confirmation', via: [:get]
  match 'users/enter_registration_code' => 'users#enter_registration_code', via: [:post]

  resource :users do
    collection do
      get :more_people_with_tags
    end
  end

  resources :users, :path => '' do
    member do
      get :settings
      get :privacy
      get :profile
      get :impersonate
      put :update_tags
      put :update_profile
      post :import_facebook_friends
      get :import_facebook_friends_finished
      get :new_notification_contact_details
      get :reset_completed_first_checkin
      get :auth_callback
      get :network
      get :tag_notifications
      put :update_tag_notifications
      put :checkin
      put :update_friend_tag
      put :update_friend_profile_tag
      get 'lists(/:tag)', action: 'lists', as: 'lists'
      get :more_locations
    end
    collection do
      get 'travelblog(/:slug)', action: 'travelblog', as: 'travelblog'
    end
  end

  resources :communities do
    member do
      get :detail
    end
    resources :community_profiles, as: "members", path: "/member" do
      member do
        get :join
        post :create
      end
      collection do
        get :invite
      end
    end
  end

  resources :users, :path => '', :only => [] do
    resources :user_locations, :path => '', :except => [:index] do
      get :notifications
      put :send_notifications
      put :update_privacy
      member do
        put :like_checkin
        put :like_comment
        post :add_comment
        post :add_note
        get :friends
      end
    end
  end

  resources :user_locations do
    collection do
      post :save_user_client_location
    end
    member do
      get 'country(/:country_id)(state/:state_id)', :action => 'show', :as => 'country_state'
      put :update_user
      put :update_photos
      get :more_friends
      put :like_checkin
      put :like_comment
      post :ask_for_advice
      post :add_comment
      post :add_note
      get :friends
    end
  end

  root :to => 'users#index'

end

app/models/user_location.rb
# == Schema Information
#
# Table name: user_locations
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  location_id    :integer
#  current        :boolean          default(FALSE)
#  ended_at       :datetime
#  residence      :boolean
#  slug           :string(255)
#  name           :string(255)
#  sent_snapshot  :text
#  custom_message :text
#  source         :string(255)
#  private        :boolean          default(FALSE)
#

class UserLocation < ActiveRecord::Base
  include Rails.application.routes.url_helpers

  belongs_to :user
  belongs_to :location
  has_many :notification_contact_details, through: :user
  has_many :user_location_assets, :dependent => :destroy
  has_many :user_location_notes, :dependent => :destroy
  has_many :user_location_tagged_users, :dependent => :destroy
  before_validation :save_or_set_location
  before_save :set_name, :make_current_and_all_prior_non_current
  accepts_nested_attributes_for :location

  attr_accessible :ended_at, :user_id, :created_at, :updated_at, :location_id, :current, :location_attributes, :residence,
    :name, :sent_snapshot, :location, :custom_message, :source, :user_location_assets_attributes, :private, :tag_list
  attr_accessor :same_as_home_location, :same_day_checkin, :used_in_total_calculation, :prior_location_id

  acts_as_votable
  acts_as_commentable
  acts_as_taggable

  accepts_nested_attributes_for :user_location_assets, :allow_destroy => true

  self.include_root_in_json = true

  serialize :sent_snapshot, Hash

  self.per_page = 10

  extend FriendlyId
  friendly_id :name_and_date, use: :slugged

  default_scope includes(:location)
  default_scope includes(:user)

  def after_initialize
    sent_snapshot |= {}
  end

  def just_created
    (((Time.now.utc - created_at) * 24 * 60 * 60).to_i < 60)
  end

  def posts?
    (posted_to_twitter? || posted_to_facebook? || (sent_snapshot[:smss] && sent_snapshot[:smss].count > 0) || (sent_snapshot[:emails] && sent_snapshot[:emails].count > 0))
  end

  def posted_to_facebook?
    posted_to_provider?(:facebook)
  end

  def posted_to_twitter?
    posted_to_provider?(:twitter)
  end

  def posted_to_provider?(provider)
    (sent_snapshot[provider] && sent_snapshot[provider] == true)
  end

  def should_generate_new_friendly_id?
    new_record?
  end

  def set_name
    self.name = location.name if ((new_record? || self.name.blank?) && location)
  end

  def message
    place_info = nil
    unless (custom_message.blank?)
      place_info = "#{custom_message} - in #{location.name}"
    else
      place_info = "#{user.first_name} arrived safely in #{location.name}"
    end
    link = user_location_url_safe(user)
    place_info << " #{created_at.strftime("%b, %d")}\n"
    place_info << "#{link}\n"
    place_info
  end

  def user_location_url_safe(user)
    user_user_location_url(user, self).gsub("localhost:3000", "www.ohheyworld.com")
  end

  def name_and_date
    the_time = (created_at) ? created_at : Time.now
    the_name = (name.blank? && location) ? location.name : name
    "#{the_name} #{the_time.strftime("%B %d %Y")}"
  end

  def make_current_and_all_prior_non_current
    return_value = true
    if self.location
      if new_record?
        user.update_attributes(completed_first_checkin: true) unless user.completed_first_checkin
        most_recent_place = user.most_recent_place
        if (!created_at || (most_recent_place && most_recent_place.location && created_at > most_recent_place.created_at))
          if (most_recent_place && most_recent_place.location && most_recent_place.location.city_name == location.city_name && most_recent_place.location.state_name == location.state_name &&
            !(most_recent_place.residence == true && location.residence != true))
            self.prior_location_id = most_recent_place.id
            return_value = false
          else
            UserLocation.where(user_id: self.user.id, current: true).where("user_locations.id IS NOT NULL").update_all(current: false)
            self.current = true
          end
        end
      end
    else
      return_value = false
    end
    return_value
  end

  def save_or_set_location
    if location && !location.id
      self.location = Location.find_or_create_by_user_input(location.user_input)
    end
  end

  def calculate_days_traveled(prior_location)
    current_ended_at = (self.ended_at) ? self.ended_at : Time.now
    days_travelled = (current_ended_at.end_of_day - self.created_at.beginning_of_day).to_i / 1.day
    if (prior_location && prior_location.created_at.to_date === current_ended_at.to_date)
      days_travelled -= 1
    end
    days_travelled
  end

  def allowed_comments(signed_in_user, creation_user)
    root_comments.where('user_id in (?) OR private = false', [signed_in_user, creation_user])
  end

  class << self
    def checkins(page)
      UserLocation.order('user_locations.created_at DESC').page(page)
    end

    def append_current_time_to_date(date)
      date = Chronic.parse("#{date} #{Time.now.strftime("%H:%M:%S")}") unless date.blank?
    end

    def locations_user_friends(user, page)
      UserLocation.where(private: false, user_id: UserFriend.user_friends_ids(user)).page(page).order('user_locations.created_at DESC')
    end

    def locations_user_friends_by_tag(user, tag, page)
      UserLocation.where(private: false, user_id: UserFriend.user_friends_by_tag_ids(user, tag)).page(page).order('user_locations.created_at DESC')
    end

    def ohw_network(current_user, page=1)
      UserLocation.where('user_id != ? AND (private = ? OR private IS NULL) AND (residence = ? OR residence IS NULL)', current_user.id, false, false).order('user_locations.created_at DESC').page(page)
    end
  end
end

app/controllers/api/user_locations_controller.rb
class Api::UserLocationsController < Api::BaseController
  before_filter :setup_user_location, only: [:user_friends_not_ohw_user, :users_at_location, :user_friends_ohw_user]
  
  def index
    @user_locations = current_user.user_locations
    render "index"
  end
  
  def user_friends_not_ohw_user
    @provider_friends = ProviderFriend.user_friends_not_ohw_user(@user, @user_location.location, true, params[:page])
    render "api/users/provider_friends"
  end
  
  def users_at_location
    @users_at_location = User.users_at_location(@user_location.location, @user, true, params[:page])
    render "api/users/index"
  end
  
  def user_friends_ohw_user
    @provider_friends = ProviderFriend.user_friends_ohw_user(@user, @user_location.location, true, params[:page])
    render "api/users/provider_friends"
  end
  
  def create
    location_params = params["user_locations.user_location"].delete(:location)
    user_location = UserLocation.new(params["user_locations.user_location"])
    user_location.location = Location.find_or_create_by_user_input(location_params[:user_input])
    user_location.source = 'api'
    user_location.save

    second_most_recent_place = current_user.second_most_recent_place
    second_most_recent_place.update_attribute(:ended_at, user_location.created_at) if second_most_recent_place && second_most_recent_place.ended_at.blank?

    unless user_location.persisted?
      user_location = current_user.current_location
      current_user.post_notifications(user_location) if user_location && current_user.completed_first_checkin
    end
    if (user_location)
      @user_locations = current_user.user_locations
      render "index"
    else
      errors = user_location.errors if user_location
      render json: {success:false, message: errors, status: :unprocessable_entity}
    end
  end
  
  def setup_user_location
    @user_location = UserLocation.find(params[:id])
    @user = @user_location.user
  end
  
end

app/helpers/user_locations_helper.rb
module UserLocationsHelper
end

app/views/user_locations/_add_trip_item.html.slim
.check-in-feed-new-item.dropdown
  = form_for @new_user_location, remote: true do |f|
    = f.error_messages
    = f.fields_for :location, Location.new do |location|
      = location.text_field :user_input, placeholder: 'Add new trip…', class: "check-in-feed-new-item-city full-width checkin-text", autocomplete: 'off'
    .dropdown-menu.check-in-feed-new-item-dropdown
      = f.text_field :created_at, placeholder: 'Arrive', class: "ui-datepicker user-profile-edit-input user-edit-created-at check-in-feed-new-item-start" 
      | until 
      = f.text_field :ended_at, placeholder: 'Depart', class: "ui-datepicker user-profile-edit-input user-edit-ended-at check-in-feed-new-item-end"
      = f.check_box :residence
      = f.label :residence, class: "check-in-feed-new-item-residence tight"
      = f.hidden_field :user_id
      = hidden_field_tag "page", params[:page]
      = f.submit "+Add a trip", class: "btn btn-small align-right tight"

app/views/user_locations/_city_locations.html.erb
<div class="m-all t-all d-all">
	<div id="locationsMap" class="profile-map"/>
	<script type="text/javascript">
	  var userLocations = new Array();
	  <% if @current_location %>
				<% location = @current_location %>
				var latitude = <%= location.latitude %>;
		    var longitude = <%= location.longitude %>;
				var address = '<%= location.address %>';
				var zoom = <%= "0" %>;
				userLocations.push([latitude, longitude, address, zoom]);
		<% end %>
	</script>
	</div>
</div>

app/views/user_locations/_comments_form.html.slim
span
  - checkin_comments = user_location.root_comments
  - form_comment = (comment) ? comment : Comment.build_from(user_location, current_user.id, "")
  = link_to "#{checkin_comments.size} Comments", "#", class: "js-comments btn btn--small btn--three zeta"
- comment_style = (@comments_closed) ? 'display:none' : ''
.js-comments-container style="#{comment_style}"
  ul.tight
  - checkin_comments.each do |comment|
    - user = comment.user
    li.comment.media.margin-ts
      .media__img.comment__img
        = link_to(profile_user_path(user)) do
          = image_tag( user.profile_picture_url('?width=96&height=96'))
      .media__body    
        = link_to(profile_user_path(user)) do  
          strong 
            = user.user_name
        span.darkgray
          |  on 
          = standard_display_date(comment.created_at)  
          br  
        span #{comment.body}
      - if !comment.link_name.blank? && !comment.link_value.blank?
        = link_to comment.link_name, comment.link_value
      .text-right  
        = form_for comment, url: {controller: 'user_locations', action: "like_comment", id: comment.id}, html: {class: 'js-comment-like-form'}, remote: true do |f|
          = f.hidden_field :id
          = button_tag(:remote => true, :class => "btn btn--small btn--three") do
            .js-comment-like.inline-block #{comment.likes.size}
            span &nbsp;
            span.icon--tight aria-hidden="true" data-icon="&#xe014;"
  - open_style = (default_open) ? '' : 'display:none'
  = form_for form_comment, url: {controller: "user_locations", action: "add_comment", id: user_location.id}, html: { style: open_style } do |f|
    = render partial: "shared/errors", locals: {errors: form_comment.errors}
    = f.text_area :body, rows: '5', class: "full-width margin-bs input-text margin-ts", placeholder: "Have a recommended activity, event, or person to meet? Leave a comment..."
    /= f.label :link_name
    /= f.text_field :link_name
    /= f.label :link_value
    /= f.text_field :link_value
    /= f.hidden_field :id
    /= f.check_box :private
    /span class="checkbox__btn" data-off-icon="&#xe011;" data-on-icon="&#xe00f;"
    = f.hidden_field :commentable_id
    = f.hidden_field :commentable_type
    = f.hidden_field :user_id
    .text-right
      = f.submit "Comment", class: "btn btn--primary"

app/views/user_locations/_first_time_checkin.html.slim
.row
  .eight.column.offset-by-two
    = form_for current_user, url: update_user_user_location_path(@user_location) do |form|
      = form.error_messages
      h2.gamma Do you want to tell your parents you’ve arrived safely with an email or SMS?
      .center-child
        .fancy-checkbox.ib
          = check_box_tag 'email_sms_parents',  1, true
          i
          label class="delta" for="email_sms_parents"
            | Yes
      .section.section-bl.clearfix 
        #parents-form
          p
            | Enter phone numbers for SMS or e-mail address to notify.
          p
            = button_tag "+Add New", id: "add-new-parent", class: "btn btn-small"
          #new-parent-entries.notify-form
            = render partial: "user_contact", locals: { details: @mom_and_dad_notification_details, f: form, placeholder_name: nil, placeholder_value: nil }
          = button_tag "Done", id: "done-with-parents", class: "btn btn-small align-left"
      h2.gamma How about your significant other, close friends, and others?
      .center-child
        .fancy-checkbox.ib
          = check_box_tag 'email_sms_friends',  1, false
          i
          label class="delta" for="email_sms_friends"
            | Yes
      .section.section-bl.clearfix 
        
        #friends-form.hide
          p
            | Enter phone numbers for SMS or e-mail address to notify.
          p
            = button_tag "+Add New", id: "add-new-friend", class: "btn btn-small"
          #new-friends-entries.notify-form
            = render partial: "user_contact", locals: { details: @friend_notification_details, f: form, placeholder_name: nil, placeholder_value: nil }
          = button_tag "Done", id: "done-with-friends", class: "btn btn-small"

      h2.gamma Do you want to tell your social media friends and followers about your arrival?
      = form.fields_for :preferences do |preference|
          .fancy-checkbox.ib
            - facebook_settings_preference = (current_user.provider_valid?('facebook')) ? "" : "facebook-settings-preference"
            = check_box_tag 'post_to_facebook', 1, current_user.provider('facebook'), {class: facebook_settings_preference}
            i
            label class="epsilon" for="post_to_facebook"
              | Yes, post my arrival on my Facebook wall

          .fancy-checkbox.ib
            = check_box_tag 'post_to_twitter', 1, false, class: "twitter-settings-preference"
            i
            label class="epsilon" for="post_to_twitter"
              | Yes, share my arrival with my Twitter followers
      .section.section-bl
        = form.submit "Complete my check in and share it!", class: "btn"

app/views/user_locations/_other_user_show.slim
- if @user_location.private
  .container Undisclosed Location
- else
  .container
    = render partial: "user_locations/city_locations"
    .m-all.t-all.d-all
      .overlay.overlay-city.text-center
        h1.beta.tight #{@current_location.name}
  .container.container--padded.container--bottom
    / Hid current_user.is_allowed_content_creation? since functionality restriction only needs to be handled in
    / user_city_location partial, and it removed entire comments form for all Standard users
    - if current_user # && current_user.is_allowed_content_creation?
      .m2-m6.t2-t8.d2-d8
        .city-checkin-item.zeta.margin-b
          .media.margin-rs.margin-ls.margin-bs
            .media__img.city-checkin-item__avatar.margin-rs
              = link_to(profile_user_path(@user)) do
                = image_tag( @user.profile_picture_url('?width=96&height=96'))
            .media__body
              = link_to(profile_user_path(@user)) do
                strong #{@user.user_name}
              span &nbsp;checked in to #{@current_location.name}
              div
                | with
                - @user_location.user_location_tagged_users.each do |user_location_tagged_user|
                  span
                    |
                    - if user_location_tagged_user.user
                      - user = user_location_tagged_user.user
                      = user.user_name
                    - elsif user_location_tagged_user.provider_friend
                      - provider_friend = user_location_tagged_user.provider_friend
                      = provider_friend.user_name
              div.darkgray Tags: #{@user_location.tag_list}
            / Hid this because the like_checkin partial also includes comments_form
            / = render partial: 'comments_form', locals: {user_location: @user_location, comment: @comment}
          .city-checkin-item__img-wrap.margin-bs
            = render partial: 'user_location_assets', locals: {user_location: @user_location}
          = render partial: "user_locations/like_checkin", locals: {user_location: @user_location, default_open: true}
    = render partial: "user_city_location"

  /.go-away-for-now
    .alt.container
      .row
        .seven.column
          h1.beta
            | #{@user.user_name} traveled to #{@current_location.name}
            - if @prior_user_location
              |  from #{@prior_user_location.location.name}!
            - else
              | !
          br
          | Checked in on #{@user_location.created_at.strftime("%B %-d, %Y")}
          - if @prior_user_location
            br
            | Previous Stop: #{link_to @prior_user_location.location.name, [@user, @prior_user_location]} from #{@prior_user_location.created_at.strftime('%-m/%-d')} -  #{@prior_user_location.ended_at.strftime('%-m/%-d')}
          - if @next_user_location
            br
            | Next Stop: #{link_to @next_user_location.location.name, [@user, @next_user_location]} on #{@next_user_location.created_at.strftime('%-m/%-d')}
            - if @next_user_location.ended_at
              |  -  #{@next_user_location.ended_at.strftime('%-m/%-d')}
          /TODO add people seen
        .five.column
          = render partial: "users/profile_badge", locals: {show_about: false}
          = link_to "See #{@user.user_name} travel profile", profile_user_path(@user)

    .sec.container
      .row
        - if @recent_locations
          | #{@user.user_name}'s recent travels
          = render(:partial => 'trips', locals: {user_locations: @recent_locations})
        = link_to "More of #{@user.first_or_last_name}'s travels", profile_user_path(@user)

app/views/user_locations/_same_user_show.slim
.container
  = render partial: "user_locations/city_locations"
  .m-all.t-all.d-all
    .overlay.overlay-city.text-center
      h1.beta.tight #{@current_location.name}
    /= render partial: "show_notifications", locals: {user_location: @user_location}
.container.container--bottom.container--padded
  .m2-m6.t2-t8.d2-d8
    .city-checkin-item.zeta.margin-b
      .media.margin-rs.margin-ls.margin-bs
        .media__img.city-checkin-item__avatar.margin-rs
          = link_to(profile_user_path(@user)) do
            = image_tag( @user.profile_picture_url('?width=96&height=96'))
        .media__body
          = link_to(profile_user_path(@user)) do
            strong #{@user.user_name}
          span  checked in to #{@current_location.name}
          div
            | with 
            - @user_location.user_location_tagged_users.each do |user_location_tagged_user|
              span.user-tag.inline-block.margin-rs
                |  
                - if user_location_tagged_user.user
                  - user = user_location_tagged_user.user
                  = user.user_name 
                - elsif user_location_tagged_user.provider_friend
                  - provider_friend = user_location_tagged_user.provider_friend
                  = provider_friend.user_name  
          /div.darkgray Tags: #{@user_location.tag_list}
      .city-checkin-item__img-wrap.margin-bs      
        = render partial: 'user_location_assets', locals: {user_location: @user_location}
      .text-right.margin-rs.margin-ls.margin-bs
        a.btn.btn--small.btn--three.js-city-checkin-item__edit-button href="#" Edit
      .city-checkin-item__edit.js-city-checkin-item__edit.margin-rs.margin-ls
        .clearfix
          = text_field_tag 'user-tag-typeahead', nil, class: "input-text m-all margin-bs", placeholder: 'Tag a friend'
        .js-users-tagged
          - @user_location.user_location_tagged_users.each do |user_location_tagged_user|
            .inline-block.margin-rs.margin-bs.darkgray.zeta.user-tag
              - if user_location_tagged_user.user
                .js-tagged-user-container
                  - user = user_location_tagged_user.user
                  = user.user_name
                  span &nbsp;
                  = link_to 'x', user_location_tagged_user, method: :delete, remote: true
                  /= link_to(profile_user_path(user)) do
                    = image_tag user.picture_url
              - elsif user_location_tagged_user.provider_friend
                .js-tagged-user-container
                  - provider_friend = user_location_tagged_user.provider_friend
                  = provider_friend.user_name
                  span &nbsp;
                  = link_to 'x', user_location_tagged_user, method: :delete, remote: true
                  /= link_to(provider_friend.link) do
                    = image_tag provider_friend.picture_url
        = form_for @user_location_tagged_user, html: {class: 'js-user-tag-form', :'data-type' => 'json'}, remote: true do |f|
          = f.hidden_field :user_location_id
          = f.hidden_field :user_id, class: 'js-user-tag-id'
          = f.hidden_field :provider_friend_id, class: 'js-provider-friend-tag-id'      
        = form_for @user_location, html: { multipart: true } do |f|
          .margin-bs
            span Attach a photo: 
            = f.fields_for :user_location_assets, @user_location.user_location_assets.build(default: true) do |field|
              = field.file_field  :asset 
          /.margin-bs    
            - checkin_type = (@user_location.residence) ? "Residence" : "Travel"
            | Check-in Type: #{checkin_type}
            = f.check_box :residence
          .clearfix 
            /= f.text_field :tag_list, class: "input-text margin-rs margin-bs m-all", placeholder: 'Check-in keywords'
            /br
            = f.submit "Save", class: "btn btn--small btn--three margin-bs margin-rs m-all"
            a.btn.btn--small.margin-bs.m-all.js-city-checkin-item__edit-cancel href="#" Cancel
        = hidden_field_tag 'js-user-location', params[:id]
        /.fb-user-advice-form
          = form_for current_user.user_provider_friends.build, url: ask_for_advice_user_location_path(@user_location), remote: true, html: {class: 'fb-friend-ask'} do |f|
            = f.email_field :email, :placeholder => "Enter their email and we'll ask them.", class: 'fb-friend-email-advice input-text margin-rs m-all'
            = f.submit "Send", class: 'fb-friend-advice-submit btn btn--small btn--comp m-all'
      div
        = render partial: "user_locations/like_checkin", locals: {user_location: @user_location, default_open: true}
  .m2-m6.t4-t6.d4-d6
		= link_to "Send Notifications", user_user_location_notifications_path(current_user.slug, @user_location.slug), class: "btn btn--primary btn--full margin-b"
  = render partial: "user_city_location"

/= link_to "See everyone in the #{@user_location.location.country_name}", country_state_user_location_path(@user_location.slug, @user_location.location.country_id)

app/views/user_locations/_trips.html.slim
- if user_locations
  - user_locations.each do |user_location|
    = render :partial => 'user_locations/trip_item', locals: { user_location: user_location }

app/views/user_locations/destroy.js.slim
= render partial: "form"