config/routes.rb
Web::Application.routes.draw do

  resources :user_location_asset

  resources :user_location_tagged_users

  namespace :admin do
    resources :users do
      member do
        get :impersonate
      end
    end
    resources :communities
  end

  match 'mission', :to => 'pages#mission'
  match 'about', :to => 'pages#about'
  match 'team', :to => 'pages#team'
  match 'privacy', :to => 'pages#privacy'
  match 'tos', :to => 'pages#tos'
  match 'faq', :to => 'pages#faq'
  match 'feedback', :to => 'pages#feedback'
  match 'jobs', :to => 'pages#jobs'
  match 'api', :to => 'pages#api'
  match 'maintenance', :to => 'pages#maintenance'
  match 'happy_customers', :to => 'pages#happy_customers'
  match 'community_guidelines', :to => 'pages#community_guidelines'
  match 'checking_in', :to => 'pages#checking_in'
  match 'welcome_kits', :to => 'pages#welcome_kits'
  match 'location_aware_group_management', :to => 'pages#location_aware_group_management'
  match 'conferences', :to => 'pages#conferences'
  match 'welcome_kits_b', :to => 'pages#welcome_kits_b'
  match 'special_thanks', :to => 'pages#special_thanks'
  match 'community_pages', :to => 'pages#community_pages'
  match 'support_us', :to => 'pages#support_us'
  match 'community_pages_community_builders', :to => 'pages#community_pages_community_builders'
  match 'communities_beta', :to => 'pages#communities_beta'
  match 'travatar', :to => 'pages#travatar'
  match 'colophon', :to => 'pages#colophon'

  get "twilio/process_sms"

  match 'twilio/process_sms' => 'twilio#process_sms'

  namespace :admin do resources :beta_access_requests end

  namespace :admin do resources :registration_codes end

  namespace :admin do resources :dashboard end

  namespace :admin do resources :countries end

  namespace :admin do resources :languages end

  namespace :admin do resources :beta_users end

  get "omniauth_callbacks_controller/facebook"

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions", passwords: "passwords", confirmations: "confirmations" } do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  devise_scope :user do
    match "/users/auth/facebook/setup" => "users/omniauth_callbacks#setup"
    match "/users/auth/facebook" => "users/omniauth_callbacks#facebook"
    match "/users/auth/facebook/callback" => "users/omniauth_callbacks#facebook"
    match "/users/auth/twitter" => "users/omniauth_callbacks#twitter"
    match "/users/auth/twitter/callback" => "users/omniauth_callbacks#twitter"
  end

  match 'users/tags(/:perma_list)' => 'users#tags', :as => 'users_tags'

  namespace :api do
    devise_for :users

    resources :users, :except=>[:destroy] do
      member do
        get 'badge'
      end
      collection do
        get 'notification_contact_details'
      end
    end

    resources :locations, :except=>[:destroy] do
      collection do
        get 'search'
      end
    end

    resources :user_locations do
      member do
        get 'user_friends_not_ohw_user'
        get 'users_at_location'
        get 'user_friends_ohw_user'
      end
    end

    resources :user_friends do
    end

    resources :user_provider_friends do
    end

    resources :user_assets do
    end

    resources :languages do
    end

    resources :user_languages do
      collection do
        put 'mass_update'
      end
    end

    resources :notification_contact_details do
    end
  end

  resources "user_provider_friends" do
    collection do
      get 'follow'
    end
  end

  resources "user_friends" do
    collection do
      get 'network'
      get 'dashboard'
      get 'travel_feed', to: 'user_friends#dashboard'
      get 'grouped_friends'
      put 'update_tag'
      get 'following/:user_id', :action => 'following', :as => 'following'
      get 'followers/:user_id', :action => 'followers', :as => 'followers'
      put :send_invitation_email
    end
  end

  resources :provider_friends do
    collection do
      get 'network'
      get 'grouped_friends'
    end
  end

  resources :locations do
    collection do
      get 'provider_friends'
    end
  end

  resources :user_searches do
    collection do
      get :site_search
      get :search_users
    end
    member do
      get :more_users_with_tag
      get :more_friends
    end
  end

  resources :beta_users

  resources :beta_access_requests

  resources :notification_contact_details

  resources :user_contacts

  resources :user_city_tips do
    member do
      put :like_city_tip
    end
  end

  resources :user_cities do
    member do
    end
    collection do
    end
  end

  match 'city_tips/:city_id(/:user_id)' => 'user_cities', action: 'city_tips', as: 'city_tips', via: [:get]

  resources :preferences

  match 'users/registration_code' => 'users#registration_code', via: [:get]
  match 'users/awaiting_confirmation' => 'users#awaiting_confirmation', via: [:get]
  match 'users/enter_registration_code' => 'users#enter_registration_code', via: [:post]

  resource :users do
    collection do
      get :more_people_with_tags
    end
  end

  resources :users, :path => '' do
    member do
      get :settings
      get :privacy
      get :profile
      get :impersonate
      put :update_tags
      put :update_profile
      post :import_facebook_friends
      get :import_facebook_friends_finished
      get :new_notification_contact_details
      get :reset_completed_first_checkin
      get :auth_callback
      get :network
      get :tag_notifications
      put :update_tag_notifications
      put :checkin
      put :update_friend_tag
      put :update_friend_profile_tag
      get 'lists(/:tag)', action: 'lists', as: 'lists'
      get :more_locations
    end
    collection do
      get 'travelblog(/:slug)', action: 'travelblog', as: 'travelblog'
    end
  end

  resources :communities do
    member do
      get :detail
    end
    resources :community_profiles, as: "members", path: "/member" do
      member do
        get :join
        post :create
      end
      collection do
        get :invite
      end
    end
  end

  resources :users, :path => '', :only => [] do
    resources :user_locations, :path => '', :except => [:index] do
      get :notifications
      put :send_notifications
      put :update_privacy
      member do
        put :like_checkin
        put :like_comment
        post :add_comment
        post :add_note
        get :friends
      end
    end
  end

  resources :user_locations do
    collection do
      post :save_user_client_location
    end
    member do
      get 'country(/:country_id)(state/:state_id)', :action => 'show', :as => 'country_state'
      put :update_user
      put :update_photos
      get :more_friends
      put :like_checkin
      put :like_comment
      post :ask_for_advice
      post :add_comment
      post :add_note
      get :friends
    end
  end

  root :to => 'users#index'

end

app/controllers/api/user_friends_controller.rb
class Api::UserFriendsController < Api::BaseController
  def index
    @user_friends = current_user.user_friends
  end

  def create
    user_friend = UserFriend.find_or_create_by_friend_id_and_user_id(params["user_friends.user_friend"]) if params["user_friends.user_friend"]["user_id"] == current_user.id
    if (user_friend)
      @user_friends = current_user.user_friends
      render "index"
    else
      errors = user_friends.errors if user_friends
      render json: {success:false, message: errors, status: :unprocessable_entity}
    end
  end

  def destroy
    user_friend = UserFriend.find(params["id"])
    user_friend.destroy if user_friend.user_id == current_user.id

    respond_to do |format|
      format.json { head :no_content }
    end
  end
end

app/controllers/user_friends_controller.rb
class UserFriendsController < ApplicationController
  
  def index
    @user_friends = UserFriend.users_with_current_location(current_user, true, params[:page])
    respond_to do |format|
      format.json
    end
  end

  def following
    @user = User.find(params[:user_id])
    @user_friends = UserFriend.all_user_friends(@user, params[:page])
  end

  def followers
    @user = User.find(params[:user_id])
    @user_friends = UserFriend.all_user_followers(@user, params[:page])
  end

  def grouped_friends
    @user = current_user
    if params[:scope] == "US"
      @country = Country.find_by_code("US")
      @user_friends = UserFriend.grouped_user_friends_not_ohw_user_in_country(@user, @country.code)
      @states = State.by_ids(@user_friends.map(&:state_id).uniq)
      @states.each do |state|
        state.user_friends = @user_friends.select{|x| x.state_name == state.name}
      end
    else
      @user_friends = UserFriend.grouped_user_friends_not_ohw_user_in_world(@user)
      @countries = Country.by_ids(@user_friends.map(&:country_id).uniq)
      @countries.each do |country|
        country.user_friends = @user_friends.select{|x| x.country_name == country.name}
      end
      render "grouped_friends_world"
    end
  end

  def show
  end

  def create
    user_friend = UserFriend.find_by_user_id_and_friend_id(params[:user_friend][:user_id], params[:user_friend][:friend_id])
    if (user_friend)
      if params[:type] == "update"
        user_friend.update_attributes(params[:user_friend])
      else
        user_friend.destroy
      end
      success = true
    else
      user_friend = UserFriend.new(params[:user_friend])
      success = user_friend.save
    end
    user_provider_friend = UserProviderFriend.ohw_user(user_friend)
    user_provider_friend.update_attributes(following: (user_friend.new_record? || user_friend.persisted?)) if user_provider_friend
    respond_to do |format|
      if success
        @user = user_friend.friend
        format.js
      else
        format.js { render json: user_friend, status: :unprocessable_entity }
      end
    end
  end
  
  def dashboard
    if current_user
      @comments_closed = true
      case params[:view]
        when "close_friends"
          @people = UserLocation.locations_user_friends_by_tag(current_user, 'Close Friends', params[:page])
        when "family"
          @people = UserLocation.locations_user_friends_by_tag(current_user, 'Family', params[:page])
        when "ohw_network"
          @people = UserLocation.ohw_network(current_user, params[:page])
        else
          @people = UserLocation.locations_user_friends(current_user, params[:page])
      end
    end
  end

  def update
    @user_friend = UserFriend.find(params[:id])
    respond_to do |format|    
      if @user_friend.update_attributes(params[:user_friend])
        format.js
      else
        format.js { render json: @user_friend, status: :unprocessable_entity }
      end
    end
  end

  def network
    @user = current_user
    input = [params[:city], params[:state], params[:country]].compact.reject { |x| x == "null"}.join(", ")
    @current_location = Location.find_or_create_by_user_input(input)
    if @current_location && @user
      @user_friends_at_location = UserFriend.user_friends_not_ohw_user_in_city_state_country(@user, @current_location, params[:page])
      @user_friends = User.user_with_ids(@user_friends_at_location.map(&:friend_id), params[:page])
    end
  end

  def update_tag
    #"user_friend"=>{"user_id"=>"2", "friend_id"=>"3"}, "tag"=>"Family"}
    @user_friend = UserFriend.find_by_user_id_and_friend_id(params[:user_friend][:user_id], params[:user_friend][:friend_id])
    tag = params[:tag]
    if @user_friend && (tag == "Unfollow" || tag == "Following")
      @user_friend.destroy
    else
      #if we dont have a user_friend we will need one b/c we must be adding
      @user_friend = UserFriend.create(params[:user_friend]) unless @user_friend
      unless (tag == "Follow" || tag == "Following")
        if @user_friend.tag_list.include?(tag)
          @user_friend.tag_list.remove(tag)
        else
          @user_friend.tag_list << tag
        end
      end
      respond_to do |format|
        if @user_friend.save
          format.js { render json: @user_friend, content_type: 'text/json' }
        else
          format.js { render json: @user_friend, status: :unprocessable_entity }
        end
      end
    end
  end

  def send_invitation_email
    NotificationMailer.delay.invite_to_ohw(current_user, params[:user][:email])
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def destroy
  end
end

app/helpers/api/user_friends_helper.rb
module Api::UserFriendsHelper
end

app/helpers/user_friends_helper.rb
module UserFriendsHelper
  def active_item(param, name, display_name, path, user_friends)
    css_class = (param == name) ? "tab-active" : "tab"
    content_tag(:li, class: 'nav-mobile__sub-item') do
      link_to(dashboard_user_friends_path + path) do
      	content_tag(:div, class: "m2-m7 t2-t4 d1-d2") do
      		content_tag(:span, '', {class: '', 'aria-hidden' => 'true', 'data-icon'=>raw("&#xe00e;")}) +
      		content_tag(:span, display_name)
      	end
    	end
    end
  end

  def user_friend_relationship(user, friend_relationship)
    (friend_relationship) ? friend_relationship : current_user.user_friends.build(friend_id: user.id)
  end

  def tag_class(is_following, friend_relationship, tag_name)
    class_text = (is_following && friend_relationship.tag_list.include?(tag_name)) ? "js-unfollow-tag" : "js-follow-tag"
    class_text << ' js-add-to-profile-tag'
  end
end

app/views/user_friends/_follow_form.html.slim
- if current_user && can_show_friend_add && user
  /- button_class = (user_friends.map(&:friend_id).include?(user.id)) ? "btn btn--fixed" : "btn btn--fixed btn--primary"
  /= form_for current_user.user_friends.build(friend_id: user.id), remote: true, html: {class: 'follow-friend'} do |f|
    = f.hidden_field :user_id
    = f.hidden_field :friend_id
    = f.hidden_field :tag_list, class: 'tag-list'
    = f.submit button_text, class: "#{button_class} friend-submit"
    = button_tag "List", class: 'btn btn--fixed btn--primary', id: 'js-profile-tag-list-btn'
  - friend_relationship = current_user.user_friends.select{ |x| x.friend_id == user.id }.first
  - is_following = (friend_relationship)
  - user_friend_relationship = user_friend_relationship(user, friend_relationship)
  - follow_text = (is_following) ? "Following" : "Follow"
  - follow_class = (is_following) ? "btn" : "btn btn--primary"
  .btn.btn-group.btn--split.btn--small class=follow_class
    = form_for user_friend_relationship, url: update_tag_user_friends_path, html: {class: 'js-add-to-profile-tag-form'}, method: :put, remote: true do |f|
      = f.hidden_field :user_id
      = f.hidden_field :friend_id
      = hidden_field_tag 'tag', follow_text, class: 'js-profile-tag-name js-profile-follow-tag'
      = f.submit follow_text, class: "btn--split__btn button js-profile-tag-button"
    button.btn--split__btn.btn--split__caret.dropdown-toggle data-toggle="dropdown"
      span.caret
    ul.dropdown-menu
      li.js-profile-hidden style="display:none"
      - @unique_friend_tags.each do |tag|
        li.js-unique-tags
          = render partial: 'user_friends/friends_tag_form', locals: {user_friend_relationship: user_friend_relationship, tag_text: tag.name, tag_name: tag.name, following: is_following}
      li.js-profile-form-text-field
        = render partial: 'user_friends/friends_tag_form', locals: {user_friend_relationship: user_friend_relationship, tag_text: nil, tag_name: nil, following: is_following}
      li.js-profile-form-unfollow style="#{(is_following) ? "" : "display:none"}"
        = render partial: 'user_friends/friends_tag_form', locals: {user_friend_relationship: user_friend_relationship, tag_text: "Unfollow", tag_name: "Unfollow", following: is_following}
      li.js-profile-form-empty style="display:none"
        = render partial: 'user_friends/friends_tag_form', locals: {user_friend_relationship: user_friend_relationship, tag_text: "empty", tag_name: "empty", following: is_following}

app/views/user_friends/_friends_follow_list.html.slim
- user_friends.each do |user_friend|
	- user = (following) ? user_friend.friend : user_friend.user
	li.media.friend-li
		= link_to(profile_user_path(user)) do
			figure class="media__img friend-li__img friend-img"
				= image_tag( user.profile_picture_url('?width=96&height=96'))
				- unless user
					figcaption class="icon-figcaption icon-facebook" aria-hidden="true" data-icon="&#xe006;"
		.media__body.friend-li__body
			strong #{user.user_name}
			- if user_profile_blurb(user) != "Undisclosed"
				div.darkgray #{truncate(user_profile_blurb(user), :length => 48)}
		.friend-li__btn.text-right
			= render partial: "user_friends/follow_form", locals: {can_show_friend_add: true, user: user }

app/views/user_friends/_friends_tag_form.html.slim
= form_for user_friend_relationship, url: update_tag_user_friends_path, html: {class: 'js-add-to-profile-tag-form'}, method: :put, remote: true do |f|
  = f.hidden_field :user_id
  = f.hidden_field :friend_id
  - if tag_name
  	- class_display = (user_friend_relationship.id) ? 'js-follow-tag' : 'js-unfollow-tag'
  	= hidden_field_tag 'tag', tag_name, class: "js-profile-tag-name"
  	= link_to tag_name, "#", class: tag_class(following, user_friend_relationship, tag_name)
  - else
    = text_field_tag 'tag', "", placeholder: "Add to new list", class: 'text-center input-text js-profile-tag-input'

app/views/user_friends/_profile_follow_form.html.slim
- if current_user && can_show_friend_add
  /- button_class = (user_friends.map(&:friend_id).include?(user.id)) ? "btn btn--fixed" : "btn btn--fixed btn--primary"
  /= form_for current_user.user_friends.build(friend_id: user.id), remote: true, html: {class: 'follow-friend'} do |f|
    = f.hidden_field :user_id
    = f.hidden_field :friend_id
    = f.hidden_field :tag_list, class: 'tag-list'
    = f.submit button_text, class: "#{button_class} friend-submit"
    = button_tag "List", class: 'btn btn--fixed btn--primary', id: 'js-profile-tag-list-btn'
  - user_friend_relationship = user_friend_relationship(user, friend_relationship)
  - follow_text = (is_following) ? "Following" : "Follow"
  - follow_class = (is_following) ? "btn" : "btn btn--primary"
  .btn.btn-group.btn--split.inline-block.margin-rs class=follow_class
    = form_for user_friend_relationship, url: update_tag_user_friends_path, html: {class: 'js-add-to-profile-tag-form'}, method: :put, remote: true do |f|
      = f.hidden_field :user_id
      = f.hidden_field :friend_id
      = hidden_field_tag 'tag', follow_text, class: 'js-profile-tag-name js-profile-follow-tag'
      = f.submit follow_text, class: "btn--split__btn button js-profile-tag-button"
    button.btn--split__btn.btn--split__caret.dropdown-toggle data-toggle="dropdown"
      span.caret
    ul.dropdown-menu
      li.js-profile-hidden style="display:none"
      - @unique_friend_tags.each do |tag|
        li.js-unique-tags
          = render partial: 'user_friends/friends_tag_form', locals: {user_friend_relationship: user_friend_relationship, tag_text: tag.name, tag_name: tag.name, following: is_following}
      li.js-profile-form-text-field
        = render partial: 'user_friends/friends_tag_form', locals: {user_friend_relationship: user_friend_relationship, tag_text: nil, tag_name: nil, following: is_following}
      li.js-profile-form-unfollow style="#{(is_following) ? "" : "display:none"}"
        = render partial: 'user_friends/friends_tag_form', locals: {user_friend_relationship: user_friend_relationship, tag_text: "Unfollow", tag_name: "Unfollow", following: is_following}
      li.js-profile-form-empty style="display:none"
        = render partial: 'user_friends/friends_tag_form', locals: {user_friend_relationship: user_friend_relationship, tag_text: "empty", tag_name: "empty", following: is_following}

app/views/user_friends/create.html.slim
h1 UserFriends#create
p Find me in app/views/user_friends/create.html.slim

app/views/user_friends/dashboard.js.erb
var content = "<%= escape_javascript(render partial: "dashboard_user", locals: {page_param: "#{params[:view]}_page", user_friends_locations: @people})%>";
var container = $("#people-location-container");
container.append(content);
<% if @people.current_page == @people.total_pages %>
$("#js-more-people-locations").hide();
<% else %>
var href = $("#js-more-people-locations").attr('href');
href = href.replace("page=<%= @people.current_page%>", "page=<%= @people.current_page + 1%>")
$("#js-more-people-locations").attr('href', href);
<% end %>

app/views/user_friends/followers.html.slim
.container.container--push-footer
	.m2-m6.t3-t7.d3-d7
	  ul#js-follow-ohw-friends
	    = render partial: 'user_friends/friends_follow_list', locals: {user_friends: @user_friends, following: false}
	  - if @user_friends.current_page < @user_friends.total_pages
	    = link_to "See More", {controller: "user_friends", action: "followers", page: @user_friends.current_page + 1}, {remote: true, id: "js-more-ohw-friends-follow", class: 'btn btn--full margin-t margin-b'}

app/views/user_friends/followers.js.erb
<%- people = @user_friends%>
var content = "<%= escape_javascript(render( partial: 'user_friends/friends_follow_list', locals: {user_friends: people, following: false} ))%>";
var container = $("#js-follow-ohw-friends");
container.append(content);
var moreLink = $("#js-more-ohw-friends-follow");
<% if people.current_page == people.total_pages %>
moreLink.hide();
<% else %>
var href = moreLink.attr('href');
href = href.replace("page=<%= people.current_page%>", "page=<%= people.current_page + 1%>")
moreLink.attr('href', href);
<% end %>

app/views/user_friends/following.html.slim
.container.container--push-footer
	.m2-m6.t3-t7.d3-d7
	  ul#js-follow-ohw-friends
	    = render partial: 'user_friends/friends_follow_list', locals: {user_friends: @user_friends, following: true}
	  - if @user_friends.current_page < @user_friends.total_pages
	    = link_to "See More", {controller: "user_friends", action: "following", page: @user_friends.current_page + 1}, {remote: true, id: "js-more-ohw-friends-follow", class: 'btn btn--full margin-t margin-b'}

app/views/user_friends/following.js.erb
<%- people = @user_friends%>
var content = "<%= escape_javascript(render( partial: 'user_friends/friends_follow_list', locals: {user_friends: people, following: true} ))%>";
var container = $("#js-follow-ohw-friends");
container.append(content);
var moreLink = $("#js-more-ohw-friends-follow");
<% if people.current_page == people.total_pages %>
moreLink.hide();
<% else %>
var href = moreLink.attr('href');
href = href.replace("page=<%= people.current_page%>", "page=<%= people.current_page + 1%>")
moreLink.attr('href', href);
<% end %>

app/views/user_friends/network.html.slim
.alt.container
  .row
    .seven.column
      - if @current_location
        #{render( :partial => 'user_locations/profile_section', :locals => {:people => @user_friends, :header_text => "Friends Checked-in to #{@current_location.name}", :footer_text => 'There are currently no other friends in', :page_param => 'page', :show_no_results => true, can_show_friend_add: true} )}

app/views/user_friends/update.html.slim
h1 UserFriends#update
p Find me in app/views/user_friends/update.html.slim